#
# GraalVM Native Image Configuration for Roya Framework
#
# This configuration file is automatically picked up by native-image
# when the graalvm plugin is included as a dependency.
#
Args = --enable-preview --no-fallback -H:+StaticExecutableWithDynamicLibC
Args = -H:IncludeResources=.*
Args = -H:+ReportExceptionStackTraces
Args = -H:-AddAllCharsets

