rootProject.name = 'roya-express'

include 'roya-api'
include 'roya-cli'
include 'roya-core'
include 'roya-examples'
include 'roya-examples-langchain4j-tutorials'
include 'roya-workflow'
include 'roya-plugins:ai'
include 'roya-plugins:auth'
include 'roya-plugins:cache'
include 'roya-plugins:database'
include 'roya-plugins:email'
include 'roya-plugins:graalvm'
include 'roya-plugins:metrics'
include 'roya-plugins:object-storage'
include 'roya-benchmarks:roya-app'
include 'roya-benchmarks:spring-app'
include 'docuRoya'
