rootProject.name = 'roya-express'

include 'roya-api'
include 'roya-core'
include 'roya-plugins:database'
include 'roya-plugins:auth'
include 'roya-plugins:metrics'
include 'roya-plugins:cache'
include 'roya-plugins:email'
include 'roya-plugins:ai'
include 'roya-plugins:object-storage'
// Vector module removed; unified under AI
// include 'roya-plugins:observability'
// include 'roya-plugins:security'
// include 'roya-cli'
include 'roya-cli'
include 'roya-examples'
