plugins {
    id 'application'
}

dependencies {
    implementation project(':roya-api')
    implementation project(':roya-core')
    implementation project(':roya-plugins:database')
    implementation project(':roya-plugins:cache')
    implementation project(':roya-plugins:metrics')
    implementation("org.slf4j:slf4j-api:${slf4jVersion}")
    runtimeOnly "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation("com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}")
}

application {
    mainClass = 'com.akilisha.oss.roya.bench.roya.PetClinicApp'
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ['--enable-preview']
}

tasks.withType(Test) {
    useJUnitPlatform()
    jvmArgs += ['--enable-preview']
}

tasks.named('run') {
    jvmArgs += ['--enable-preview']
}
