name: Create Development Builds

jobs:
  build_dev_android:
    name: Build Android
    type: build # This job type creates a production build for Android
    params:
      platform: android
      profile: development
  build_dev_ios:
    name: Build iOS device
    type: build # This job type creates a production build for iOS
    params:
      platform: ios
      profile: development
  build_dev_ios_simulator:
    name: Build iOS simulator
    type: build # This job type creates a production build for iOS
    params:
      platform: ios
      profile: development-simulator