name: Create Production Builds

jobs:
  build_android:
    name: Build Android
    type: build # This job type creates a production build for Android
    params:
      platform: android
  build_ios:
    name: Build iOS device
    type: build # This job type creates a production build for iOS
    params:
      platform: ios