plugins {
    id 'java-library'
}

dependencies {
    implementation project(':roya-api')
    implementation 'io.helidon.config:helidon-config:4.0.3'

    // AWS S3 SDK v2 (MinIO-compatible)
    implementation 'software.amazon.awssdk:s3:2.25.62'
    implementation 'software.amazon.awssdk:auth:2.25.62'
    implementation 'software.amazon.awssdk:regions:2.25.62'

    implementation 'org.slf4j:slf4j-api:2.0.10'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['--enable-preview']
}

tasks.withType(Test).configureEach {
    jvmArgs += ['--enable-preview']
}


