server.port=8070
management.endpoints.web.exposure.include=health,metrics,info

# Access logs
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
server.tomcat.basedir=.
server.tomcat.accesslog.pattern=%h %l %u %t \"%r\" %s %b %D
# Optional: more web logs
logging.level.org.springframework.web=INFO
