plugins {
    id 'java-library'
}

dependencies {
    implementation project(':roya-api')
    implementation project(':roya-core')
    implementation project(':roya-plugins:ai')

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'
    implementation 'org.slf4j:slf4j-api:2.0.9'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['--enable-preview']
}

tasks.withType(Test).configureEach {
    jvmArgs += ['--enable-preview']
}


